class_homepage:
    path:     /
    defaults: { _controller: classBundle:Default:home }
class_add:
    path:     /add
    defaults: { _controller: classBundle:classe:add }
class_read:
    path:     /read
    defaults: { _controller: classBundle:classe:read }
class_delete:
    path:     /delete/{id}
    defaults: { _controller: classBundle:classe:delete }
class_update:
    path:     /update/{id}
    defaults: { _controller: classBundle:classe:update }
class_addTimeTable:
    path:     /addTimeTable
    defaults: { _controller: classBundle:classe:addTimeTable }
class_readTimeTable:
    path:     /readTimeTable
    defaults: { _controller: classBundle:classe:readTimeTable }
class_deleteTimeTable:
    path:     /deleteTimeTable/{id}
    defaults: { _controller: classBundle:classe:deleteTimeTable }
class_updateTimeTable:
    path:     /updateTimeTable/{id}
    defaults: { _controller: classBundle:classe:updateTimeTable }
class_searchTimeTable:
    path:     /searchTimeTable
    defaults: { _controller: classBundle:classe:searchTimeTable }
class_home:
    path:     /home
    defaults: { _controller: classBundle:Default:home }
class_pdf:
    path:     /pdfM
    defaults: { _controller: classBundle:classe:indexm }
class_createTtable:
    path:     /createTtable
    defaults: { _controller: classBundle:classe:createTtable }
class_Ttime:
    path:     /readT
    defaults: { _controller: classBundle:classe:readTime }
class_searchTtime:
    path:     /searchT
    defaults: { _controller: classBundle:classe:searchTtime }




