<?php

namespace classBundle\Repository;

/**
 * classRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class classRepository extends \Doctrine\ORM\EntityRepository
{
}
