<?php

namespace classBundle\Repository;

/**
 * nomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class nomRepository extends \Doctrine\ORM\EntityRepository
{
}
