<?php

namespace classBundle\Repository;

/**
 * timeTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class timetableRepository extends \Doctrine\ORM\EntityRepository
{
}
